config/routes.rb
Todo::Application.routes.draw do
  resources :users
  resources :lists
  resources :tasks
  resources :completed_tasks, only: [:create]
  resource :sessions

  root :to => 'tasks#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name, :description
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  
  attr_accessible :name, :due_at, :list_id
  validates :name, presence: true
  validates :list, presence: true
  
  scope :complete, where(:completed => true)
  scope :incomplete, where(:completed => false)
  scope :newest_first, order("created_at DESC")
  scope :completed_first, order("completed DESC")
 
  def due_date
    if due_at
      "Due: #{due_at}"
    else
      nil
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :email
  
  def set_logged_in
    update_attribute(:last_login_at, Time.now)
  end
  
  def full_name
    "#{first_name} #{last_name}"
  end
  
  def to_s
    full_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  before_filter :require_current_user
  
  protected
  
  def require_current_user
    unless current_user
      flash[:notice] = "You must be signed in to view this page"
      redirect_to new_sessions_path
    end
  end
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end
  
  def set_current_user(user_id)
    session[:user_id] = user_id
    User.find(session[:user_id]).set_logged_in
  end
  
  def logout_current_user
    session[:user_id] = nil
  end
end

app/controllers/completed_tasks_controller.rb
class CompletedTasksController < ApplicationController
  def create
    @task = Task.find(params[:id])
    @task.completed = true
    @task.save
    flash[:notice] = "Completed task"
    redirect_to tasks_path
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_current_user
  
  def new
    
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user
      flash[:notice] = "Logged in!"
      set_current_user(user.id)
    else
      flash[:notice] = "No user found with that email"
    end    
    redirect_to root_path
  end
  
  def destroy
    logout_current_user
    flash[:notice] = "Logged out"
    redirect_to new_sessions_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @lists = List.all(:include => :tasks)
    @task = Task.new
  end
   
  def create
    @task = Task.new(params[:task])
    if @task.save
      flash[:notice] = "Created task!"
      redirect_to tasks_path
    else
      @tasks = Task.all
      @lists = List.all
      flash[:notice] = "Could not save"
      render 'index'
    end
  end
  
  def edit
    @task = Task.find(params[:id])
    @lists = List.all
  end
  
  def update
    @task = Task.find(params[:id])
    @lists = List.all
     if @task.update_attributes(params[:task])
        flash[:notice] = "Updated task!"
        redirect_to tasks_path
      else
        flash[:notice] = "Could not save"
        render 'edit'
      end
  end
  
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:notice] = "Deleted task"
    redirect_to tasks_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/completed_tasks_helper.rb
module CompletedTasksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if current_user %>
		Welcome, <%= current_user %> <%= current_user.last_name %>
		<%= link_to "Logout", sessions_path, method: :delete %>
	<% end %>
	<p><%= flash[:notice] %></p>
	<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Listing lists</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lists.each do |list| %>
  <tr>
    <td><%= list.name %></td>
    <td><%= list.description %></td>
    <td><%= link_to 'Show', list %></td>
    <td><%= link_to 'Edit', edit_list_path(list) %></td>
    <td><%= link_to 'Destroy', list, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p>
  <b>Name:</b>
  <%= @list.name %>
</p>

<p>
  <b>Description:</b>
  <%= @list.description %>
</p>


<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/tasks/_form.html.erb
<ul>
	<% @task.errors.full_messages.each do |message| %>
       <li><%= message %></li>
    <% end %>
</ul>


<%= form_for @task do |form| %>
	<div>Name: <%= form.text_field :name %></div>
	<div>Due Date: <%= form.datetime_select :due_at %></div>
	<div>List: <%= form.collection_select :list_id, @lists, :id, :name, :prompt => true %>
	<%= form.submit %>
<% end %>

app/views/tasks/_task.html.erb
<li class="completed-<%= task.completed %>">
	<%= task.name %>
		Created: <%= time_ago_in_words(task.created_at) %> ago
	<%= task.due_date %>
	<% unless task.completed? %>
		<%= button_to "Complete", completed_tasks_path(id: task.id) %>
		<%= link_to "Edit", edit_task_path(task) %> 
	<% end %>
	<%= link_to "(x)", task, method: :delete, confirm: "Are you sure?" %>
</li>

app/views/tasks/edit.html.erb
<h2>Edit Task</h2>
<%= render "form" %>

app/views/tasks/index.html.erb
<h2>Tasks</h2>

<% @lists.each do |list| %>
	<strong><%= list.name %>: <%= list.tasks.count %></strong>
	<ul>
		<%= render list.tasks %>
	</ul>
<% end %>

<h2>New Task</h2>

<%= render 'form' %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Last login at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.email %></td>
    <td><%= time_ago_in_words(user.last_login_at) %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Last login at:</b>
  <%= @user.last_login_at %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>